
patterns = [ # Desugb Patterbs used by GEML*
    'abstract.*factory',
    # M 'adapter',
    'factory',
    'bridge',
    # M 'command',
    'composite',
    'decorator',
    'factory.*method',
    # M 'iterator',
    'observer',
    # M 'proxy',
    'singleton',
    # M 'state',
    'strategy',
    # M 'template.*method',
    # M'template',
    'visitor',
    #'builder',
    #'prototype',
    'facade',
    'flyweight',
    #'chain',
    #'chain.*of.*responsability',
    #'chain.*responsability',
    'mediator',
    'memento',
]